### ISSUE TITLE
Does it work with Node 10

### ISSUE THREAD

**Issue by tibinthomas** [tewen/gtd-scripts#5]
(node:17040) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/tmp/fr-1544083108.json'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1187:35)
    at sum.concat._.reduce.then (C:\Users\tibin\Desktop\Translate\gtd-scripts\translate-json:61:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tibinthomas** [comment]
It works. I got this error coz I didn't have a tmp folder in the root of C drive.
