### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by maximelebreton** [tewen/gtd-scripts#6]
Hello, and thank you for your script,
but i can't make it works...

`node translate-json <api-key> fixtures/translate-json/en.json fr`

result:
```
Translating Afrikaans to fr
(node:14976) UnhandledPromiseRejectionWarning: Error: Forbidden
    at PromiseRequest.Request.callback (E:\_sandbox\translate-json\node_modules\superagent\lib\node\index.js:706:15)
    at parser (E:\_sandbox\translate-json\node_modules\superagent\lib\node\index.js:916:18)
    at Stream.res.on (E:\_sandbox\translate-json\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at Stream.emit (events.js:182:13)
    at Unzip.unzip.on (E:\_sandbox\translate-json\node_modules\superagent\lib\node\unzip.js:55:12)
    at Unzip.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:14976) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14976) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Run on `Windows 10` & `node 11.2.0`

Thanks!

**Comment by paulotokarskiglinski** [comment]
This error occurs because there are no 'catch()' treatment. Please add a 'catch()' treatment in every Promise:

Promise.all(_.reduce(destinationCodes, (sum, languageKey) => {
        const fileName = _.template('<%= languageKey %>.json')({
            languageKey,
            timeStamp: moment().unix()
        });
        return sum.concat(_.reduce(iterLeaves(JSON.parse(fs.readFileSync(path.resolve(inputFile), 'utf-8')), undefined, undefined, languageKey), (promiseChain, fn) => {
            return promiseChain.then(fn);
        }, Promise.resolve()).then((payload) => {
            fs.writeFileSync(fileName, JSON.stringify(payload));
        }).then(_.partial(console.log, 'Successfully translated all nodes, file output at ' + fileName)
        ).catch(err => console.log(err)));
    }, [])).then(() => {
        process.exit();
    }).catch(err => console.log(err));
